name: mitul_s_application165
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.17.0
  permission_handler: ^10.0.0
  flutter_contacts: ^1.1.5
  images_picker: ^1.2.11
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
        - asset: assets/fonts/LatoBold.ttf
          weight: 700
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
    - family: Playfair Display
      fonts: 
        - asset: assets/fonts/PlayfairDisplayRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplayRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplayRomanBold.ttf
          weight: 700
